services:
  pgvector:
    hostname: db
    image: pgvector/pgvector:0.7.4-pg17
    container_name: pgvector
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=vector
      - POSTGRES_PASSWORD=vector123
      - POSTGRES_HOST_AUTH_METHOD=trust
      - TZ='Asia/Jakarta'
    volumes:
      - ./pgvector/data:/var/lib/postgresql/data
      - ./pgvector/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pgvector_network

networks:
  pgvector_network: