services:
  qdrant:
    image: qdrant/qdrant:v1.12.1
    container_name: qdrant
    restart: unless-stopped
    ports:
      - 6333:6333
      - 6334:6334
      - 6335:6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant/data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__API_KEY=889600f2-089f-4e3a-8bc5-07eab5e93d34

configs:
  qdrant_config:
    content: |
      log_level: INFO      